const userdata = [
  {
    fname: "Khushi",
    lname: "Bajaj",
    phoneNumber: "+919589635472",
    gender: "Female",
    email: "khushi@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Sneha",
    lname: "Naik",
    phoneNumber: "+919704321654",
    gender: "Female",
    email: "sneha@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Anjali",
    lname: "Parwani",
    phoneNumber: "+919821476532",
    gender: "Female",
    email: "anjali@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Khyati",
    lname: "Hegde",
    phoneNumber: "+919663452189",
    gender: "Female",
    email: "khyati@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Sayali",
    lname: "Kawatkar",
    phoneNumber: "+919845612378",
    gender: "Female",
    email: "sayali@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Sanika",
    lname: "Dhuri",
    phoneNumber: "+919876543210",
    gender: "Female",
    email: "sanika.sharma@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Ravi",
    lname: "Raj",
    phoneNumber: "+919874563210",
    gender: "Male",
    email: "ravi.raj@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Sandeep",
    lname: "Thakur",
    phoneNumber: "+919765432109",
    gender: "Male",
    email: "sandeep.thakur@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Vishal",
    lname: "Jain",
    phoneNumber: "+919986754321",
    gender: "Male",
    email: "vishal.jain@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Pradeep",
    lname: "Gupta",
    phoneNumber: "+919922884455",
    gender: "Male",
    email: "pradeep.gupta@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Ajay",
    lname: "Mishra",
    phoneNumber: "+919589635472",
    gender: "Male",
    email: "ajay.mishra@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Anand",
    lname: "Singh",
    phoneNumber: "+919704321654",
    gender: "Male",
    email: "anand.singh@gmail.com",
    serviceLookingFor: "other",
  },
  {
    fname: "Vikram",
    lname: "Yadav",
    phoneNumber: "+919821476532",
    gender: "Male",
    email: "vikram.yadav@gmail.com",
    serviceLookingFor: "other",
  },
];
